export interface Icon{
    name: IconName;
    shape: IconShape;
}
export type IconShape = 'outline' | 'sharp' | ''; // empty is filled
export type IconName = 
"accessibility"             |
"add"                       |
"add"                       |
"airplane"                  |
"alarm"                     |
"albums"                    |
"alert"                     |
"alert"                     |
"american"                  |
"analytics"                 |
"aperture"                  |
"apps"                      |
"archive"                   |
"arrow"                     |
"arrow"                     |
"arrow"                     |
"arrow"                     |
"arrow"                     |
"arrow"                     |
"arrow"                     |
"arrow"                     |
"arrow"                     |
"arrow"                     |
"arrow"                     |
"arrow"                     |
"at"                        |
"at"                        |
"attach"                    |
"backspace"                 |
"bag"                       |
"bag"                       |
"bag"                       |
"bag"                       |
"bag"                       |
"balloon"                   |
"ban"                       |
"bandage"               |
"bar"               |
"barbell"               |
"barcode"               |
"baseball"              |
"basket"                |
"basketball"                |
"battery"               |
"battery"               |
"battery"               |
"battery"               |
"beaker"                |
"bed"               |
"beer"              |
"bicycle"               |
"bluetooth"             |
"boat"              |
"body"              |
"bonfire"               |
"book"              |
"bookmark"              |
"bookmarks"             |
"bowling"               |
"briefcase"             |
"browsers"              |
"brush"             |
"bug"               |
"build"             |
"bulb"              |
"bus"               |
"business"              |
"cafe"              |
"calculator"                |
"calendar"              |
"calendar"              |
"calendar"              |
"call"              |
"camera"                |
"camera"                |
"car"               |
"car"               |
"card"              |
"caret"             |
"caret"             |
"caret"             |
"caret"             |
"caret"             |
"caret"             |
"caret"             |
"caret"             |
"cart"              |
"cash"              |
"cellular"              |
"chatbox"               |
"chatbox"               |
"chatbubble"                |
"chatbubble"                |
"chatbubbles"               |
"checkbox"              |
"checkmark"             |
"checkmark"             |
"checkmark"             |
"checkmark"             |
"chevron"               |
"chevron"               |
"chevron"               |
"chevron"               |
"chevron"               |
"chevron"               |
"chevron"               |
"chevron"               |
"clipboard"             |
"close"             |
"close"             |
"cloud"             |
"cloud"             |
"cloud"             |
"cloud"             |
"cloud"             |
"cloud"             |
"cloudy"                |
"cloudy"                |
"code"              |
"code"              |
"code"              |
"code"              |
"cog"               |
"color"             |
"color"             |
"color"             |
"color"             |
"compass"               |
"construct"             |
"contract"              |
"contrast"              |
"copy"              |
"create"                |
"crop"              |
"cube"              |
"cut"               |
"desktop"               |
"diamond"               |
"dice"              |
"disc"              |
"document"              |
"document"              |
"document"              |
"document"              |
"documents"             |
"download"              |
"duplicate"             |
"ear"               |
"earth"             |
"easel"             |
"egg"               |
"ellipse"               |
"ellipsis"              |
"ellipsis"              |
"ellipsis"              |
"ellipsis"              |
"enter"             |
"exit"              |
"expand"                |
"extension"             |
"eye"               |
"eye"               |
"eyedrop"               |
"fast"              |
"female"                |
"file"              |
"file"              |
"file"              |
"film"              |
"filter"                |
"filter"                |
"finger"                |
"fish"              |
"fitness"               |
"flag"              |
"flame"             |
"flash"             |
"flash"             |
"flashlight"                |
"flask"             |
"flower"                |
"folder"                |
"folder"                |
"football"              |
"footsteps"             |
"funnel"                |
"game"              |
"gift"              |
"git"               |
"git"               |
"git"               |
"git"               |
"git"               |
"git"               |
"glasses"               |
"globe"             |
"golf"              |
"grid"              |
"hammer"                |
"hand"              |
"hand"              |
"happy"             |
"hardware"              |
"headset"               |
"heart"             |
"heart"             |
"heart"             |
"heart"             |
"heart"             |
"help"              |
"help"              |
"help"              |
"home"              |
"hourglass"             |
"ice"               |
"id"                |
"image"             |
"images"                |
"infinite"              |
"information"               |
"information"               |
"invert"                |
"journal"               |
"key"               |
"keypad"                |
"language"              |
"laptop"                |
"layers"                |
"leaf"              |
"library"               |
"link"              |
"list"              |
"list"              |
"locate"                |
"location"              |
"lock"              |
"lock"              |
"log"               |
"log"               |
"magnet"                |
"mail"              |
"mail"              |
"mail"              |
"male"              |
"male"              |
"man"               |
"map"               |
"medal"             |
"medical"               |
"medkit"                |
"megaphone"             |
"menu"              |
"mic"               |
"mic"               |
"mic"               |
"mic"               |
"moon"              |
"move"              |
"musical"               |
"musical"               |
"navigate"              |
"navigate"              |
"newspaper"             |
"notifications"             |
"notifications"             |
"notifications"             |
"notifications"             |
"nuclear"               |
"nutrition"             |
"open"              |
"options"               |
"paper"             |
"partly"                |
"pause"             |
"pause"             |
"paw"               |
"pencil"                |
"people"                |
"people"                |
"person"                |
"person"                |
"person"                |
"person"                |
"phone"             |
"phone"             |
"pie"               |
"pin"               |
"pint"              |
"pizza"             |
"planet"                |
"play"              |
"play"              |
"play"              |
"play"              |
"play"              |
"play"              |
"play"              |
"play"              |
"play"              |
"play"              |
"podium"                |
"power"             |
"pricetag"              |
"pricetags"             |
"print"             |
"prism"             |
"pulse"             |
"push"              |
"qr"                |
"radio"             |
"radio"             |
"radio"             |
"rainy"             |
"reader"                |
"receipt"               |
"recording"             |
"refresh"               |
"refresh"               |
"reload"                |
"reload"                |
"remove"                |
"remove"                |
"reorder"               |
"reorder"               |
"reorder"               |
"repeat"                |
"resize"                |
"restaurant"                |
"return"                |
"return"                |
"return"                |
"return"                |
"ribbon"                |
"rocket"                |
"rose"              |
"sad"               |
"save"              |
"scale"             |
"scan"              |
"scan"              |
"school"                |
"search"                |
"search"                |
"send"              |
"server"                |
"settings"              |
"shapes"                |
"share"             |
"share"             |
"shield"                |
"shield"                |
"shield"                |
"shirt"             |
"shuffle"               |
"skull"             |
"snow"              |
"sparkles"              |
"speedometer"               |
"square"                |
"star"              |
"star"              |
"stats"             |
"stop"              |
"stop"              |
"stopwatch"             |
"storefront"                |
"subway"                |
"sunny"             |
"swap"              |
"swap"              |
"sync"              |
"sync"              |
"tablet"                |
"tablet"                |
"telescope"             |
"tennisball"                |
"terminal"              |
"text"              |
"thermometer"               |
"thumbs"                |
"thumbs"                |
"thunderstorm"              |
"ticket"                |
"time"              |
"timer"             |
"today"             |
"toggle"                |
"trail"             |
"train"             |
"transgender"               |
"trash"             |
"trash"             |
"trending"              |
"trending"              |
"triangle"              |
"trophy"                |
"tv"                |
"umbrella"              |
"unlink"                |
"videocam"              |
"videocam"              |
"volume"                |
"volume"                |
"volume"                |
"volume"                |
"volume"                |
"walk"              |
"wallet"                |
"warning"               |
"watch"             |
"water"             |
"wifi"              |
"wine"              |
"woman"